card/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
	url(r'^$', views.CardListView.as_view(), name='list'),
	url(r'^new$', views.CardCreateView.as_view(), name='new'),
	url(r'^delete/(?P<pk>\d+)$', views.CardDeleteView.as_view(), name='delete'),
	url(r'^update/(?P<pk>\d+)$', views.CardUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)$', views.CardDetailView.as_view(), name='detail'),
]

teach_to_the_cards/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from card.views import (
    CardListView, CardCreateView, CardDeleteView, 
    CardUpdateView, CardDetailView
)

urlpatterns = [
    url(r'^', include('card.urls', namespace='card')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

card/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Card(models.Model):
	question = models.TextField(unique=True)
	answer = models.TextField()
	description = models.TextField(blank=True)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.question

	def get_absolute_url(self):
		return reverse('card:detail', args=[self.id])

card/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Card


class CardListView(ListView):
	model = Card
	template_name = 'list_card.html'


class CardCreateView(CreateView):
	model = Card
	template_name = 'create_card.html'
	success_url = reverse_lazy('card:list')
	fields = ['question', 'answer', 'description',]


class CardDeleteView(DeleteView):
	model = Card
	template_name = 'delete_card.html'
	success_url = reverse_lazy('card:list')


class CardUpdateView(UpdateView):
	model = Card
	template_name = 'update_card.html'
	success_url = reverse_lazy('card:list')	
	fields = ['question', 'answer', 'description',]


class CardDetailView(DetailView):
	model = Card
	template_name = 'detail_card.html'
	context_object_name = 'card'

teach_to_the_cards/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>

	<link rel="stylesheet" type="text/css" href="{% static 'lib/Materialize/dist/css/materialize.min.css' %}">

	<title></title>
</head>
<body>
	
	<header>
		<nav class="light-green darken-2 z-depth-0">
			<div class="nav-wrapper">
				<ul class="left">
					<li><a href="{% url 'card:list' %}">Home</a></li>
					<li><a href="{% url 'card:new' %}">Create</a></li>
				</ul>
			</div>
		</nav>
	</header>

	{% block content %} 
	{% endblock %}

	<script type="text/javascript" src="{% static 'lib/jquery/dist/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'lib/Materialize/dist/js/materialize.min.js' %}"></script>
	
</body>
</html>

teach_to_the_cards/templates/create_card.html
{% extends 'base.html' %}

{% block content %} 
<div class="container">
	<div class="row">
		<form action='' method='post'>
			{% csrf_token %}
			{{ form.as_p }}
			<input type='submit' value='Submit'>
		</form>
	</div>
</div>
{% endblock %}

teach_to_the_cards/templates/delete_card.html
{% extends 'base.html' %}

{% block content %} 
<div class="container">
	<div class="row">
		<form action='' method='post'>
			{% csrf_token %}
			<p>Are you sure you want to delete "{{ object }}"?</p>
   			<input type="submit" value="Confirm" />
		</form>
	</div>
</div>
{% endblock %}

teach_to_the_cards/templates/detail_card.html
{% extends 'base.html' %}

{% block content %} 
<div class="container">
	<div class="row">
		<h3>{{ card.question }}</h3>
		<p class='flow-text'>{{ card.answer }}</p>
		<hr>
		<p class='flow-text'>{{ card.description }}</p>
		<hr>
		<p>Created: <time>{{ card.created }}</time></p>
	</div>
</div>
{% endblock %}

teach_to_the_cards/templates/list_card.html
{% extends 'base.html' %}

{% block content %} 
<table>
	<thead>
		<tr>
			<th>Question</th>
			<th>Answer</th>
			<th>Description</th>
			<th>Created</th>
			<th>Tools</th>
		</tr>
	</thead>

	<tbody>
		{% for card in object_list %}
			<tr>	
				<td><a href="{% url 'card:detail' pk=card.id %}">{{ card.question|truncatechars:50 }}</a></td>
				<td>{{ card.answer|truncatechars:50 }}</td>
				<td>{{ card.description|truncatechars:50 }}</td>
				<td>{{ card.created }}</td>
				<td><a href="{% url 'card:delete' pk=card.id %}">Delete</a>|<a href="{% url 'card:update' pk=card.id %}">Update</a></td>
			</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

teach_to_the_cards/templates/update_card.html
{% extends 'base.html' %}

{% block content %} 
<div class="container">
	<div class="row">
		<form action='' method='post'>
			{% csrf_token %}
			{{ form.as_p }}
    		<input type="submit" value="Update" />
		</form>
	</div>
</div>
{% endblock %}